export const RECIPIENTS_MOCK = [
    {
        name: "Мухаммад Мухаммадов",
        id: 1,
        desc: "Top G",
        birthdate: "today",
        city: "Moscow",
        phone: "+87898989797789",
        uni: "BMSTU",
    },
    {
        name: "Махершалалхашбаз Али",
        id: 2,
        desc: "Готов сняться в крутых фильмах",
        birthdate: "16-02-1974",
        city: "Окленд",
        phone: "+878989897977",
        uni: "New York University",
        avatar: "https://www.mercurynews.com/wp-content/uploads/2017/02/mahershala-2.jpg?w=1024&h=681",
    },
    {
        name: "Анна Иванова",
        id: 5,
        desc: "Программист, увлечённая разработкой мобильных приложений",
        birthdate: "12-05-1990",
        city: "Москва",
        phone: "+7 999 555-01-23",
        uni: "Московский государственный университет",
    },
    {
        name: "Dimiter Marinov",
        id: 6,
        desc: "Инженер-конструктор, специализирующийся на разработке сложных механизмов",
        birthdate: "03-08-1985",
        city: "Санкт-Петербург",
        phone: "+7 888 444-56-78",
        uni: "Санкт-Петербургский политехнический университет Петра Великого",
        avatar: "https://avatars.mds.yandex.net/i?id=44fe45e152d5ca314d3e1ac6a6b0f020_l-8338702-images-thumbs&n=13",
    },
    {
        draftId: null,
        draftRecipientsLen: 0,
    },
];
