export const RECIPIENTS_MOCK = [
    {
        name: "Мухаммад Мухаммадов",
        id: 1,
        desc: "Фронтбэнд разработчик в VK",
        birthdate: "2000-10-10",
        city: "Moscow",
        phone: "+87898989797789",
        uni: "BMSTU",
    },
    {
        name: "Махершалалхашбаз Али",
        id: 2,
        desc: "Готов сняться в крутых фильмах",
        birthdate: "1974-02-16",
        city: "Окленд",
        phone: "+878989897977",
        uni: "New York University",
        avatar: "/images/mahershala-2.webp",
    },
    {
        name: "Анна Иванова",
        id: 5,
        desc: "Программист, увлечённая разработкой мобильных приложений",
        birthdate: "1990-05-12",
        city: "Москва",
        phone: "+7 999 555-01-23",
        uni: "Московский государственный университет",
    },
    {
        name: "Dimiter Marinov",
        id: 6,
        desc: "Инженер-конструктор, специализирующийся на разработке сложных механизмов",
        birthdate: "1985-08-03",
        city: "Санкт-Петербург",
        phone: "+7 888 444-56-78",
        uni: "Санкт-Петербургский политехнический университет Петра Великого",
        avatar: "/images/i.webp",
    },
    {
        draftId: null,
        draftRecipientsLen: 0,
    },
];
